var data = [
    {
        tit: [
            {
                titimg: "image/suningyigou/a_1.png",
                tita1: "手机",
                tithref1:"https://shouji.suning.com/phone2018.html?safp=d488778a.homepagev8.126605238628.1&safpn=10001",
                titxie1: "/",
                tita2: "运营商",
                tithref2:"https://yys.suning.com/",
                titxie2: "/",
                tita3: "智能数码",
                tithref3:"https://pindao.suning.com/city/zhinengshuma.html?safp=d488778a.homepagev8.126605238628.3&safpn=10001",
                titxie3: "",
                tita4:"",
                tithref4:"",
            },
            {
                titimg: "image/suningyigou/a_2.png",
                tita1: "家用电器",
                tithref1:"https://dianqi.suning.com/?safp=d488778a.homepagev8.0.a3e7be4eb3&safpn=10001",
                titxie1: "",
                tita2: "",
                tithref2:"",
                titxie2: "",
                tita3: "",
                tithref3:"",
                titxie3: "",
                tita4:"",
                tithref4:"",
            },
            {
                titimg: "image/suningyigou/a_3.png",
                tita1: "厨卫",
                tithref1:"https://pindao.suning.com/city/chuwei.html",
                titxie1: "/",
                tita2: "生活家电",
                tithref2:"https://pindao.suning.com/city/xiaojiadian.html",
                titxie2: "/",
                tita3: "厨具",
                tithref3:"https://pindao.suning.com/city/chuiju.html",
                titxie3: "",
                tita4:"",
                tithref4:"",
            },
            {
                titimg: "image/suningyigou/a_4.png",
                tita1: "电脑办公",
                tithref1:"https://pindao.suning.com/city/diannao.html",
                titxie1: "/",
                tita2: "相机",
                tithref2:"https://pindao.suning.com/city/shuma.htm",
                titxie2: "/",
                tita3: "厨具",
                tithref3:"https://list.suning.com/0-20529-0.html",
                titxie3: "",
                tita4:"",
                tithref4:"",
            },
            {
                titimg: "image/suningyigou/a_5.png",
                tita1: "家居",
                tithref1:"https://search.suning.com/%E5%AE%B6%E7%BA%BA/",
                titxie1: "/",
                tita2: "家具",
                tithref2:"https://pindao.suning.com/city/jiajuguan.html",
                titxie2: "/",
                tita3: "家装",
                tithref3:"https://pindao.suning.com/city/jiazhuang.html",
                titxie3: "/",
                tita4:"家纺",
                tithref4:"https://list.suning.com/0-161645-0.html",
            },
            {
                titimg: "image/suningyigou/a_6.png",
                tita1: "食品",
                tithref1:"https://list.suning.com/0-500353-0.html",
                titxie1: "/",
                tita2: "酒水",
                tithref2:"https://search.suning.com/%E9%85%92/",
                titxie2: "/",
                tita3: "生鲜",
                tithref3:"https://sxs.suning.com/sxspc_huadong.html",
                titxie3: "/",
                tita4:"特产",
                tithref4:"https://china.suning.com/",
            },
            {
                titimg: "image/suningyigou/a_7.png",
                tita1: "美妆",
                tithref1:"https://cuxiao.suning.com/scms/rfmypc.html",
                titxie1: "/",
                tita2: "个护",
                tithref2:"https://binggo.suning.com/meizhuang_temai.htm",
                titxie2: "/",
                tita3: "清洁",
                tithref3:"https://list.suning.com/0-161657-0.html",
                titxie3: "/",
                tita4:"宠物",
                tithref4:"https://list.suning.com/0-500552-0.html",
            },
            {
                titimg: "image/suningyigou/a_8.png",
                tita1: "母婴",
                tithref1:"https://redbaby.suning.com/",
                titxie1: "/",
                tita2: "玩具",
                tithref2:"https://cuxiao.suning.com/scms/wanjuju.html",
                titxie2: "/",
                tita3: "车床",
                tithref3:"https://cuxiao.suning.com/scms/tczycardayPC.html",
                titxie3: "/",
                tita4:"童装",
                tithref4:"https://cuxiao.suning.com/scms/tztxcxye.html",
            },
            {
                titimg: "image/suningyigou/a_9.png",
                tita1: "运动",
                tithref1:"https://sports.suning.com/",
                titxie1: "/",
                tita2: "户外",
                tithref2:"https://list.suning.com/0-420008-0.html",
                titxie2: "/",
                tita3: "足球",
                tithref3:"https://shop.suning.com/30001902/index.html",
                titxie3: "/",
                tita4:"骑行",
                tithref4:"https://list.suning.com/0-420010-0.html",
            },
            {
                titimg: "image/suningyigou/a_10.png",
                tita1: "女装",
                tithref1:"https://fashion.suning.com/",
                titxie1: "/",
                tita2: "男装",
                tithref2:"https://fashion.suning.com/",
                titxie2: "/",
                tita3: "内衣",
                tithref3:"https://fashion.suning.com/",
                titxie3: "/",
                tita4:"鞋靴",
                tithref4:"https://fashion.suning.com/",
            },
            {
                titimg: "image/suningyigou/a_11.png",
                tita1: "箱包",
                tithref1:"https://pindao.suning.com/city/xiangbao.html",
                titxie1: "/",
                tita2: "钟表",
                tithref2:"https://pindao.suning.com/city/zhongbiaoyanjing.html",
                titxie2: "/",
                tita3: "珠宝",
                tithref3:"https://pindao.suning.com/city/zhubao.html",
                titxie3: "/",
                tita4:"艺术",
                tithref4:"https://pindao.suning.com/city/stamp.html",
            },
            {
                titimg: "image/suningyigou/a_12.png",
                tita1: "汽车",
                tithref1:"https://pindao.suning.com/city/snqcsh.html",
                titxie1: "/",
                tita2: "电摩",
                tithref2:"https://search.suning.com/%E7%94%B5%E5%8A%A8%E8%BD%A6/&ci=504570&iy=-1&st=0?safp=d488778a.homepage1.99345513004.68&safpn=10001#search-path",
                titxie2: "/",
                tita3: "汽车用品",
                tithref3:"https://car.suning.com/qcypnew.html",
                titxie3: "",
                tita4:"",
                tithref4:"",
            },
            {
                titimg: "image/suningyigou/a_13.png",
                tita1: "图书",
                tithref1:"https://book.suning.com/",
                titxie1: "/",
                tita2: "艺术",
                tithref2:"https://list.suning.com/0-502325-0.html",
                titxie2: "/",
                tita3: "原版",
                tithref3:"https://search.suning.com/%E5%8E%9F%E7%89%88%E4%B9%A6/",
                titxie3: "/",
                tita4:"文学",
                tithref4:"https://list.suning.com/0-502319-0.html",
            },
            {
                titimg: "image/suningyigou/a_14.png",
                tita1: "医用健康",
                tithref1:"https://yao.suning.com/",
                titxie1: "/",
                tita2: "计生情趣",
                tithref2:"https://yao.suning.com/",
                titxie2: "",
                tita3: "",
                tithref3:"",
                titxie3: "",
                tita4:"",
                tithref4:"",
            },
            {
                titimg: "image/suningyigou/a_15.png",
                tita1: "理财",
                tithref1:"https://licai.suning.com/lcportal/licaiIndex.htm?channelCode=PC_YGMstation",
                titxie1: "/",
                tita2: "分期",
                tithref2:"https://paypassport.suning.com/ids/login?service=https%3A%2F%2Frxf.suning.com%2Fepps-cpf%2Fauth%3FtargetUrl%3Dhttps%253A%252F%252Frxf.suning.com%252Fepps-cpf%252FaccountMgt%252FassetOverview.do&loginTheme=defaultTheme",
                titxie2: "/",
                tita3: "保险",
                tithref3:"https://www.snisc.cn/",
                titxie3: "/",
                tita4:"便民",
                tithref4:"https://pay.suning.com/epp-epw/lifecenter/index.action",
            },
        ],
        goods: [
            {
               goodshref: "http://th.suning.com/cpm/calCpmClick?adtype=3&sid=17055118&tid=1705611820200923&click_id=Muf7NFc0Bp7GFOsL37oKFeshwp&ap=MDZjZjczMjkwNzk1ZjVkMTBhMDQwYzFlMTNjYWEwYzV8NDAwMDAxMTIzfDE3MDU2MTE4MjAyMDA5MjN8MTcwNTUxMTh8aHR0cHM6Ly9zaG9wLnN1bmluZy5jb20vMzAwMDAyNDQvaW5kZXguaHRtbHxDUE18MjAyMC0wOS0yMyAxOTowMzo0MXxNdWY3TkZhMEJwN0dGRVl0TXwxMTcuMTM2LjM4LjEzMnwwfGh0dHBzOi8vd3d3LnN1bmluZy5jb20vfDQyODk3ODc0OXwxNjAwODU5MDAxMTc2MjExNDh8MzAxNDEzNDV8MTl8MTAwfDEwLjEwNi4xMy4zNXwwfDB8cGN8fGJjYmZkYTBkZTIwNzBjZjY4NTQwZjUwYjQxMjc4MDJmfDE3MDU2MTE4fDQwMDAwMTEyM3x8fHx8aG9tZXBhZ2V2OHxodHRwczovL29zcy5zdW5pbmcuY29tL2FkcHAvY3JlYXRpdmVfa2l0L21hdGVyaWFsL3BpY3R1cmUvMjAyMDA5MDktMzhhNjE2M2Y3ODVlNDEyYmIyYzNhNzhjZWE0OTAwOWJkMjgxZTRjYmZkNGY0NzQ1LmpwZ3wxNzI6MSwxNzM6MiwxNzQ6MHxudWxsfA%3D%3D&clickUrl=https%3A%2F%2Fshop.suning.com%2F30000244%2Findex.html%3Fadtype%3D3",
                goodsimg: "image/suningyigou/1.png",
            },
            {
               goodshref: "http://th.suning.com/cpm/calCpmClick?adtype=3&sid=17096673&tid=1709667320200923&click_id=Muf7NFa0Bp7GFJpn37pTePzPbP&ap=MDQwZjYxODNiYWM1MzE2ODhkNTVkZmEwYzI5Yzc4Mjl8MTAwMDEwNTEwfDE3MDk2NjczMjAyMDA5MjN8MTcwOTY2NzN8aHR0cHM6Ly9zaG9wLnN1bmluZy5jb20vMzAwMDM1MzcvaW5kZXguaHRtbHxjcG18MjAyMC0wOS0yMyAxOTowMzo0MXxNdWY3TkZhMEJwN0dGRVl0TXwxMTcuMTM2LjM4LjEzMnwzMDAwMHxodHRwczovL3d3dy5zdW5pbmcuY29tL3w0MjkwMTYyODJ8MTYwMDg1OTAwMTE3NjIxMTQ4fDMwMTU0MjEwfDE5fDEwMHwxMC4xMDYuMTMuMzV8MXwxfHBjfHxiYTQ5ZTNlNDI3ZjViM2NkNmExMjhhZjM2NDc3ZDNhZnx8MzAwMDAwNjE1fHx8fHxob21lcGFnZXY4fGh0dHBzOi8vb3NzLnN1bmluZy5jb20vYWRwcC9jcmVhdGl2ZV9raXQvbWF0ZXJpYWwvcGljdHVyZS8yMDIwMDkyMi04ZTAzZTljZjVhZWM0ZTI3YTY2Yjk4ODVhY2VhODI0ZmI2ODY5OWY1OTkzNTRiMzcuanBnfHxudWxsfA%3D%3D&clickUrl=https%3A%2F%2Fshop.suning.com%2F30003537%2Findex.html%3Fadtype%3D3",
                goodsimg: "image/suningyigou/2.png",
            },
            {
               goodshref: "http://th.suning.com/cpm/calCpmClick?adtype=3&sid=17103630&tid=1710363020200923&click_id=Muf7NFa0Bp7GFCqY37pfto1iHL&ap=OTk4MWMwODNiOTk0N2FlNWIxMWEzZDBjM2U2MzkzYjd8MTAwMDEwNTExfDE3MTAzNjMwMjAyMDA5MjN8MTcxMDM2MzB8aHR0cHM6Ly9jdXhpYW8uc3VuaW5nLmNvbS9zY21zL3pob25ncWl1eXVlbGk5MTIuaHRtbHxjcG18MjAyMC0wOS0yMyAxOTowMzo0MXxNdWY3TkZhMEJwN0dGRVl0TXwxMTcuMTM2LjM4LjEzMnwwfGh0dHBzOi8vd3d3LnN1bmluZy5jb20vfDQyOTAxOTY4M3wxNjAwODU5MDAxMTc2MjExNDh8MzAxNTQ1MjF8MTl8MTAwfDEwLjEwNi4xMy4zNXwwfHxwY3x8NzMxNDJjNmY0ZDg4ODRiYWMyOGIxOWZjMTJlZjA2NTl8fDMwMDAwMDYxNnx8fHx8aG9tZXBhZ2V2OHxodHRwczovL29zcy5zdW5pbmcuY29tL2FkcHAvY3JlYXRpdmVfa2l0L21hdGVyaWFsL3BpY3R1cmUvMjAyMDA5MjMtMmFjOThlOTk0ZDIxNGM1NzliMDZkMGMxOGMwM2IwYmYxOGFlMjE1NTVjMjU0ODdjLmpwZ3x8bnVsbHw%3D&clickUrl=https%3A%2F%2Fcuxiao.suning.com%2Fscms%2Fzhongqiuyueli912.html%3Fadtype%3D3",
                goodsimg: "image/suningyigou/3.png",
            },
            {
               goodshref: "http://th.suning.com/cpm/calCpmClick?adtype=3&sid=17101035&tid=1710103520200923&click_id=Muf7NFb0Bp7GFKyM37pbKYA9uN&ap=ZjJmZjQ4MmU2NDM3YzZjZDYzYzQ2Y2QwM2U1NmZmNjF8MTAwMDEwNTEyfDE3MTAxMDM1MjAyMDA5MjN8MTcxMDEwMzV8aHR0cHM6Ly9zaG9wLnN1bmluZy5jb20vMzAwMDAwMTEvMTAzODM3MTAuaHRtbHxjcG18MjAyMC0wOS0yMyAxOTowMzo0MXxNdWY3TkZhMEJwN0dGRVl0TXwxMTcuMTM2LjM4LjEzMnw2MDAwMHxodHRwczovL3d3dy5zdW5pbmcuY29tL3w0MjkxNjExNTd8MTYwMDg1OTAwMTE3NjIxMTQ4fDMwMTQ5NTQ2fDE5fDEwMHwxMC4xMDYuMTMuMzV8MXwxfHBjfHw0ODU1YmRkYWRhYjEyMDRkN2M3ZTdhZTQ2YzFjNDgwMXx8MzAwMDAwNjE3fHx8fHxob21lcGFnZXY4fGh0dHBzOi8vb3NzLnN1bmluZy5jb20vYWRwcC9jcmVhdGl2ZV9raXQvbWF0ZXJpYWwvcGljdHVyZS8yMDIwMDkxOC1lZmFiN2Y3ZTAwNGU0OTliYTQ4YzYzZjkwYTdhODBiMDBjNjIyZTE5NzY1NjQ4YTguanBnfHxudWxsfA%3D%3D&clickUrl=https%3A%2F%2Fshop.suning.com%2F30000011%2F10383710.html%3Fadtype%3D3",
                goodsimg: "image/suningyigou/4.png",
            },
        ]
    },
]
var ul = document.querySelector(".box_left ul");
    for (var m = 0; m < data[0].tit.length; m++) {
        ul.innerHTML += `
        <li>
        <img src="${data[0].tit[m].titimg}" alt="">
        <a href="${data[0].tit[m].tithref1}">${data[0].tit[m].tita1}</a>
        <em>${data[0].tit[m].titxie1}</em>
        <a href="${data[0].tit[m].tithref2}">${data[0].tit[m].tita2}</a>
        <em>${data[0].tit[m].titxie2}</em>
        <a href="${data[0].tit[m].tithref3}">${data[0].tit[m].tita3}</a>
        <em>${data[0].tit[m].titxie3}</em>
        <a href="${data[0].tit[m].tithref4}">${data[0].tit[m].tita4}</a>
    </li>
        `
    }
var uls = document.querySelector(".dingwei ul");
    for (var i = 0; i < data[0].goods.length; i++) {
        uls.innerHTML += `
        <li>
        <a href="${data[0].goods[i].goodshref}">
        <img src="${data[0].goods[i].goodsimg}" alt="">
        </a>
        </li>
        `
    }
